<#
.SYNOPSIS
  Builds FRENCH_REVIEW.md from the shipped French DefInjected XML, for TRANSLATIONS.md's
  "Systematic French review by Virginie" (2026-09-30).
.DESCRIPTION
  This mod has one French file (Mod/Languages/French/DefInjected/ThingDef/JoyPreservation.xml)
  and no Mod/Defs directory of its own: the three ThingDefs it translates are injected by
  Mod/Patches/EponaInstruments.xml (PatchOperationConditional/PatchOperationAdd), not shipped as
  plain Defs. English is read from that patch's inline <label>/<description> fields, matched by
  defName. Original: the source mod (Epona Instruments Standalone by Outremer) has no
  non-English source text in this repository (ATTRIBUTION.md does not record one) — Original
  equals English throughout, noted once here rather than on every row.
#>
param(
    [string]$Root = (Split-Path $PSScriptRoot -Parent),
    [string]$OutFile = (Join-Path (Split-Path $PSScriptRoot -Parent) 'FRENCH_REVIEW.md')
)

function Get-Entries($path) {
    $entries = [ordered]@{}
    if (-not (Test-Path $path)) { return $entries }
    $xml = [xml](Get-Content $path -Raw -Encoding UTF8)
    foreach ($node in $xml.LanguageData.ChildNodes) {
        if ($node.NodeType -ne 'Element') { continue }
        $entries[$node.Name] = $node.InnerText
    }
    return $entries
}

$frenchRoot = Join-Path $Root 'Mod/Languages/French'
$patchFile = Join-Path $Root 'Mod/Patches/EponaInstruments.xml'
$patch = [xml](Get-Content $patchFile -Raw -Encoding UTF8)
$defNodes = $patch.SelectNodes('//ThingDef[defName]')
$enByDef = @{}
foreach ($d in $defNodes) {
    $enByDef[$d.defName] = @{ label = $d.label; description = $d.description }
}

$frenchFiles = Get-ChildItem $frenchRoot -Recurse -Filter *.xml | Sort-Object FullName
$out = New-Object System.Text.StringBuilder
[void]$out.AppendLine("# French review")
[void]$out.AppendLine()
[void]$out.AppendLine("Generated by `_tools/Generate-FrenchReview.ps1` for TRANSLATIONS.md's systematic French review.")
[void]$out.AppendLine("**Original column: same as English throughout.** The source mod (Epona Instruments")
[void]$out.AppendLine("Standalone by Outremer) has no non-English source text recorded in this repository")
[void]$out.AppendLine("(see ATTRIBUTION.md); English is the only source available for every row.")
[void]$out.AppendLine()
[void]$out.AppendLine("Generated $(Get-Date -Format 'yyyy-MM-dd'), revision: working tree after the pipes/accordion sound-capture run.")
[void]$out.AppendLine()

foreach ($ff in $frenchFiles) {
    $rel = $ff.FullName.Substring($frenchRoot.Length + 1) -replace '\\', '/'
    $frEntries = Get-Entries $ff.FullName
    if ($frEntries.Count -eq 0) { continue }

    [void]$out.AppendLine("## $rel")
    [void]$out.AppendLine()
    [void]$out.AppendLine("| Key or path | Original | English | French |")
    [void]$out.AppendLine("|---|---|---|---|")
    foreach ($key in $frEntries.Keys) {
        $fr = $frEntries[$key]
        $parts = $key -split '\.'
        $defName = $parts[0]
        $field = $parts[1]
        $en = $null
        if ($enByDef.ContainsKey($defName)) { $en = $enByDef[$defName][$field] }
        if ($null -eq $en) { $en = '*(not found — check by hand)*' }
        $orig = $en
        $flag = if ($fr -match '\?\?\?|TODO' -or ($fr -match '\{PAWN_gender' -and $fr -notmatch '\{PAWN_gender \? ')) { ' | ?' } else { '' }
        $origCell = ($orig -replace '\|', '\|') -replace "`n", ' '
        $enCell = ($en -replace '\|', '\|') -replace "`n", ' '
        $frCell = ($fr -replace '\|', '\|') -replace "`n", ' '
        $keyCell = $key -replace '\|', '\|'
        [void]$out.AppendLine("| $keyCell | $origCell | $enCell | $frCell$flag |")
    }
    [void]$out.AppendLine()
}

[System.IO.File]::WriteAllText($OutFile, $out.ToString(), (New-Object System.Text.UTF8Encoding($false)))
Write-Output "wrote $OutFile"
